from pymongo import MongoClient
from dotenv import load_dotenv
import os


load_dotenv()


client = MongoClient(os.getenv('MONGO_URI'))
db = client['automobile_db']
collection = db['automobiles']


collection.delete_many({})
print("Successfully deleted all documents from the automobiles collection.")


automobiles = [
    {
        "manufacturer": "BMW",
        "model": "M2 Coupe",
        "full_name": "BMW M2 Competition Coupe",
        "price": 73602,
        "fuel": "Gasoline",
        "chassis": "Coupe",
        "transmission": "Automatic",
        "engine": "3.0L",
        "power_kw": 353,
        "power_hp": 480,
        "acceleration": 4,
        "fuel_consumption": 9.7,
    },
    {
        "manufacturer": "BMW",
        "model": "M3 Competition M xDrive Sedan",
        "full_name": "BMW M3 Competition xDrive Sedan",
        "price": 101150,
        "fuel": "Diesel",
        "chassis": "Sedan",
        "transmission": "Automatic",
        "engine": "3.0L",
        "power_kw": 390,
        "power_hp": 530,
        "acceleration": 3.5,
        "fuel_consumption": 10.1,
    },
    {
        "manufacturer": "BMW",
        "model": "M4 CS Coupe",
        "full_name": "BMW M4 Competition Coupe",
        "price": 154284,
        "fuel": "Diesel",
        "chassis": "Coupe",
        "transmission": "Automatic",
        "engine": "3.0L",
        "power_kw": 405,
        "power_hp": 551,
        "acceleration": 3.4,
        "fuel_consumption": 10.2,
    },
    {
        "manufacturer": "BMW",
        "model": "M8 Coupe",
        "full_name": "BMW M8 Competition Coupe",
        "price": 165172,
        "fuel": "Gasoline",
        "chassis": "Coupe",
        "transmission": "Automatic",
        "engine": "4.4L",
        "power_kw": 441,
        "power_hp": 600,
        "acceleration": 3.3,
        "fuel_consumption": 11.3,
    },
    {
        "manufacturer": "BMW",
        "model": "X4 M",
        "full_name": "BMW X4 M Competition",
        "price": 103768,
        "fuel": "Gasoline",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "3.0L",
        "power_kw": 353,
        "power_hp": 480,
        "acceleration": 4,
        "fuel_consumption": 10.7,
    },
    {
        "manufacturer": "BMW",
        "model": "X5 M Competition",
        "full_name": "BMW X5 M Competition",
        "price": 145894,
        "fuel": "Gasoline",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "4.4L",
        "power_kw": 460,
        "power_hp": 625,
        "acceleration": 3.9,
        "fuel_consumption": 12.9,
    },
    {
        "manufacturer": "BMW",
        "model": "X6 M Competition",
        "full_name": "BMW X6 M Competition",
        "price": 148929,
        "fuel": "Gasoline",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "4.4L",
        "power_kw": 460,
        "power_hp": 625,
        "acceleration": 3.9,
        "fuel_consumption": 12.7,
    },
    {
        "manufacturer": "Porsche",
        "model": "718 Spyder RS",
        "full_name": "Porsche 718 Spyder RS",
        "price": 171854,
        "fuel": "Gasoline",
        "chassis": "Cabriolet",
        "transmission": "Automatic",
        "engine": "4.0L",
        "power_kw": 368,
        "power_hp": 500,
        "acceleration": 3.4,
        "fuel_consumption": 12.7,
    },
    {
        "manufacturer": "Porsche",
        "model": "911 GT3",
        "full_name": "Porsche 911 GT3",
        "price": 225817,
        "fuel": "Gasoline",
        "chassis": "Coupe",
        "transmission": "Manual",
        "engine": "4.0L",
        "power_kw": 375,
        "power_hp": 510,
        "acceleration": 3.9,
        "fuel_consumption": 13.8,
    },
    {
        "manufacturer": "Porsche",
        "model": "Taycan Turbo GT",
        "full_name": "Porsche Taycan Turbo GT",
        "price": 250016,
        "fuel": "Electric",
        "chassis": "Limousine",
        "transmission": "Automatic",
        "engine": "Electric",
        "power_kw": 580,
        "power_hp": 789,
        "acceleration": 2.3,
        "energy_consumption": 21.6,
    },
    {
        "manufacturer": "Porsche",
        "model": "Macan Turbo",
        "full_name": "Porsche Macan Turbo",
        "price": 119561,
        "fuel": "Electric",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "Electric",
        "power_kw": 430,
        "power_hp": 584,
        "acceleration": 3.3,
        "energy_consumption": 20.7,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "C 63 S E PERFORMANCE",
        "full_name": "Mercedes-AMG C 63 S E PERFORMANCE",
        "price": 110790,
        "fuel": "Hybrid (Gasoline)",
        "chassis": "Sedan",
        "transmission": "Automatic",
        "engine": "2.0L",
        "power_kw": 500,
        "power_hp": 680,
        "acceleration": 3.4,
        "fuel_consumption": 7.3,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "S 63 E Performance",
        "full_name": "Mercedes-AMG S 63 E PERFORMANCE",
        "price": 214660,
        "fuel": "Hybrid (Gasoline)",
        "chassis": "Limousine",
        "transmission": "Automatic",
        "engine": "4.0L",
        "power_kw": 590,
        "power_hp": 802,
        "acceleration": 3.3,
        "fuel_consumption": 4.6,
        "energy_consumption": 22.2,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "GLC 63 S E PERFORMANCE Coupe",
        "full_name": "Mercedes-AMG GLC 63 S E PERFORMANCE Coupe",
        "price": 129570,
        "fuel": "Hybrid (Gasoline)",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "2.0L",
        "power_kw": 375,
        "power_hp": 510,
        "acceleration": 3.9,
        "fuel_consumption": 13.8,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "G 63",
        "full_name": "Mercedes-AMG G 63",
        "price": 206651,
        "fuel": "Gasoline",
        "chassis": "SUV",
        "transmission": "Automatic",
        "engine": "4.0L",
        "power_kw": 430,
        "power_hp": 585,
        "acceleration": 4.4,
        "fuel_consumption": 14.7,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "CLA 45 S 4MATIC+ Coupe",
        "full_name": "Mercedes-AMG CLA 45 S 4MATIC+ Coupe",
        "price": 74350,
        "fuel": "Gasoline",
        "chassis": "Coupe",
        "transmission": "Automatic",
        "engine": "2.0L",
        "power_kw": 310,
        "power_hp": 421,
        "acceleration": 4.1,
        "fuel_consumption": 8.9,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "GT 63 S E PERFORMANCE",
        "full_name": "Mercedes-AMG GT 63 S E PERFORMANCE",
        "price": 229241,
        "fuel": "Hybrid (Gasoline)",
        "chassis": "Coupe",
        "transmission": "Automatic",
        "engine": "4.0L",
        "power_kw": 450,
        "power_hp": 612,
        "acceleration": 2.8,
        "fuel_consumption": 8.2,
    },
    {
        "manufacturer": "Mercedes-AMG",
        "model": "SL 63 S E PERFORMANCE",
        "full_name": "Mercedes-AMG SL 63 S E PERFORMANCE",
        "price": 235191,
        "fuel": "Hybrid (Gasoline)",
        "chassis": "Cabriolet",
        "transmission": "Automatic",
        "engine": "4.0L",
        "power_kw": 450,
        "power_hp": 612,
        "acceleration": 2.9,
        "fuel_consumption": 7.9,
    }
]


collection.insert_many(automobiles)
print("Successfully populated the database with the automobiles data.")
